
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __KMS_KMS_RTP_ENUMTYPES_ENUM_TYPES_H__
#define __KMS_KMS_RTP_ENUMTYPES_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "kmsrtpsdescryptosuite.h" */
GType kms_rtp_sdes_crypto_suite_get_type (void);
#define KMS_TYPE_RTP_SDES_CRYPTO_SUITE (kms_rtp_sdes_crypto_suite_get_type())

G_END_DECLS

#endif /* __KMS_KMS_RTP_ENUMTYPES_ENUM_TYPES_H__ */

/* Generated data ends here */

