/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __HTTP_MARSHAL_MARSHAL_H__
#define __HTTP_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:STRING,ENUM (/home/vbccam/kms-omni-build/kms-elements/src/server/implementation/HttpServer/http-marshal.list:2) */
extern
void http_marshal_VOID__STRING_ENUM (GClosure     *closure,
                                     GValue       *return_value,
                                     guint         n_param_values,
                                     const GValue *param_values,
                                     gpointer      invocation_hint,
                                     gpointer      marshal_data);


G_END_DECLS

#endif /* __HTTP_MARSHAL_MARSHAL_H__ */
