/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ____KMS_WEBRTC_MARSHAL_MARSHAL_H__
#define ____KMS_WEBRTC_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* BOOLEAN:VOID (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-marshal.list:1) */
extern
void __kms_webrtc_marshal_BOOLEAN__VOID (GClosure     *closure,
                                         GValue       *return_value,
                                         guint         n_param_values,
                                         const GValue *param_values,
                                         gpointer      invocation_hint,
                                         gpointer      marshal_data);

/* BOOLEAN:OBJECT (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-marshal.list:2) */
extern
void __kms_webrtc_marshal_BOOLEAN__OBJECT (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* VOID:STRING,OBJECT (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-marshal.list:3) */
extern
void __kms_webrtc_marshal_VOID__STRING_OBJECT (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* BOOLEAN:STRING (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-marshal.list:4) */
extern
void __kms_webrtc_marshal_BOOLEAN__STRING (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* BOOLEAN:STRING,OBJECT (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-marshal.list:5) */
extern
void __kms_webrtc_marshal_BOOLEAN__STRING_OBJECT (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);


G_END_DECLS

#endif /* ____KMS_WEBRTC_MARSHAL_MARSHAL_H__ */
