
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __KMS_KMS_WEBRTC_ENUMTYPES_ENUM_TYPES_H__
#define __KMS_KMS_WEBRTC_ENUMTYPES_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "kmswebrtcdatachannelpriority.h" */
GType kms_web_rtc_data_channel_priority_get_type (void);
#define KMS_TYPE_WEB_RTC_DATA_CHANNEL_PRIORITY (kms_web_rtc_data_channel_priority_get_type())

/* enumerations from "kmswebrtcdatachannelstate.h" */
GType kms_web_rtc_data_channel_state_get_type (void);
#define KMS_TYPE_WEB_RTC_DATA_CHANNEL_STATE (kms_web_rtc_data_channel_state_get_type())

G_END_DECLS

#endif /* __KMS_KMS_WEBRTC_ENUMTYPES_ENUM_TYPES_H__ */

/* Generated data ends here */

