/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ____KMS_WEBRTC_DATA_MARSHAL_MARSHAL_H__
#define ____KMS_WEBRTC_DATA_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* INT:BOOLEAN,INT,INT,STRING,STRING (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-data-marshal.list:1) */
extern
void __kms_webrtc_data_marshal_INT__BOOLEAN_INT_INT_STRING_STRING (GClosure     *closure,
                                                                   GValue       *return_value,
                                                                   guint         n_param_values,
                                                                   const GValue *param_values,
                                                                   gpointer      invocation_hint,
                                                                   gpointer      marshal_data);

/* OBJECT:UINT (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-data-marshal.list:2) */
extern
void __kms_webrtc_data_marshal_OBJECT__UINT (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);

/* BOXED:VOID (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-data-marshal.list:3) */
extern
void __kms_webrtc_data_marshal_BOXED__VOID (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:STRING,BOOLEAN (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-data-marshal.list:4) */
extern
void __kms_webrtc_data_marshal_VOID__STRING_BOOLEAN (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);

/* VOID:STRING,UINT (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-data-marshal.list:5) */
extern
void __kms_webrtc_data_marshal_VOID__STRING_UINT (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:STRING,INT (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-data-marshal.list:6) */
extern
void __kms_webrtc_data_marshal_VOID__STRING_INT (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* INT:STRING,BOOLEAN,INT,INT,STRING,STRING (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-data-marshal.list:7) */
extern
void __kms_webrtc_data_marshal_INT__STRING_BOOLEAN_INT_INT_STRING_STRING (GClosure     *closure,
                                                                          GValue       *return_value,
                                                                          guint         n_param_values,
                                                                          const GValue *param_values,
                                                                          gpointer      invocation_hint,
                                                                          gpointer      marshal_data);

/* OBJECT:STRING,UINT (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-data-marshal.list:8) */
extern
void __kms_webrtc_data_marshal_OBJECT__STRING_UINT (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* BOXED:STRING,VOID (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/webrtcendpoint/kms-webrtc-data-marshal.list:9) */
extern
void __kms_webrtc_data_marshal_BOXED__STRING_VOID (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);


G_END_DECLS

#endif /* ____KMS_WEBRTC_DATA_MARSHAL_MARSHAL_H__ */
