
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __KMS_KMS_ELEMENTS_ENUMTYPES_ENUM_TYPES_H__
#define __KMS_KMS_ELEMENTS_ENUMTYPES_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "kmsencodingrules.h" */
GType kms_encoding_rules_get_type (void);
#define KMS_TYPE_ENCODING_RULES (kms_encoding_rules_get_type())

/* enumerations from "kmshttpendpointmethod.h" */
GType kms_http_endpoint_method_get_type (void);
#define KMS_TYPE_HTTP_ENDPOINT_METHOD (kms_http_endpoint_method_get_type())

G_END_DECLS

#endif /* __KMS_KMS_ELEMENTS_ENUMTYPES_ENUM_TYPES_H__ */

/* Generated data ends here */

