/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ____KMS_MARSHAL_MARSHAL_H__
#define ____KMS_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* UINT:UINT (/home/vbccam/kms-omni-build/kms-elements/src/gst-plugins/rtcpdemux/kms-marshal.list:1) */
extern
void __kms_marshal_UINT__UINT (GClosure     *closure,
                               GValue       *return_value,
                               guint         n_param_values,
                               const GValue *param_values,
                               gpointer      invocation_hint,
                               gpointer      marshal_data);


G_END_DECLS

#endif /* ____KMS_MARSHAL_MARSHAL_H__ */
